config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'games#index'
  resources :games, only: [:new, :create, :show, :update]
  resources :pieces, only: [:update]

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :white_player, class_name: :user
  has_one :black_player, class_name: :user
  has_many :pieces

  after_create :populate_board!

  # scope :available, -> {
  # 	joins("LEFT OUTER JOIN users ON users.game_id = games.id").
  # 	group("games.id").
  # 	having("count(games.id) < 2")
  # }

  scope :available, -> { where('black_player_id IS NULL OR white_player_id IS NULL') }

  def check?
    #game is in check if either black or white king is in check
    king_is_in_check?('black') || king_is_in_check?('white')
  end

  def king_is_in_check?(color)
    #finds king by color
    king = pieces.find_by(type: "King", color: color)
    #returns array of all opposing pieces
    opponents = pieces.where.not(color: color)
    #loops through each opposing piece to determine if they have a valid move
    #that can capture king
    opponents.each do |opponent|
      return true if opponent.valid_move?(king.x, king.y)
    end
    false
  end
  private

  def populate_board!
    pieces.create(x: 'A', y: '1', type: 'Rook', color: 'white')
    pieces.create(x: 'B', y: '1', type: 'Knight', color: 'white')
    pieces.create(x: 'C', y: '1', type: 'Bishop', color: 'white')
    pieces.create(x: 'D', y: '1', type: 'Queen', color: 'white')
    pieces.create(x: 'E', y: '1', type: 'King', color: 'white')
    pieces.create(x: 'F', y: '1', type: 'Bishop', color: 'white')
    pieces.create(x: 'G', y: '1', type: 'Knight', color: 'white')
    pieces.create(x: 'H', y: '1', type: 'Rook', color: 'white')
    pieces.create(x: 'A', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'B', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'C', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'D', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'E', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'F', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'G', y: '2', type: 'Pawn', color: 'white')
    pieces.create(x: 'H', y: '2', type: 'Pawn', color: 'white')

    pieces.create(x: 'A', y: '8', type: 'Rook', color: 'black')
    pieces.create(x: 'B', y: '8', type: 'Knight', color: 'black')
    pieces.create(x: 'C', y: '8', type: 'Bishop', color: 'black')
    pieces.create(x: 'D', y: '8', type: 'Queen', color: 'black')
    pieces.create(x: 'E', y: '8', type: 'King', color: 'black')
    pieces.create(x: 'F', y: '8', type: 'Bishop', color: 'black')
    pieces.create(x: 'G', y: '8', type: 'Knight', color: 'black')
    pieces.create(x: 'H', y: '8', type: 'Rook', color: 'black')
    pieces.create(x: 'A', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'B', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'C', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'D', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'E', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'F', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'G', y: '7', type: 'Pawn', color: 'black')
    pieces.create(x: 'H', y: '7', type: 'Pawn', color: 'black')
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper

  def index
    @games = Game.available
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create
    redirect_to game_path(@game.id)
  end

  def update
    current_game.update_attributes(game_params)
  end

  def show
    @game = Game.find(params[:id])
    gon.pieces_hash = render_pieces(@game) # call the helper function and get the hash. will be passed onto the view
    # Pusher.trigger("game-#{@game.id}", 'refresh_page', {:message => "Your Move!"})
  end

  private

  def current_game
    @current_game ||= Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:score, :result, :white_player_id, :black_player_id, :turn)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def render_pieces(game) # this function takes a game object as input and spit out a hash with "xy" ('a8') as key and "color_type" ("black_rook") as value
    render_hash = {}
    game.pieces.each do |piece|
      pos_id = piece.x + piece.y.to_s
      piece_class = piece.color + '_' + piece.type.downcase # gon.piece_class = white_knight
      render_hash[pos_id] = [piece_class, piece.id]
    end
    render_hash
  end
end

app/views/games/index.html.erb
<div class="front-hero">
	<div class="welcome col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4 text-center">
		<p>welcome to</p>
		<h1 class="star">JediChess</h1>
		<%= image_tag("lightsaber.png") %>
		<p>developed by Yan Hu, Eric Orellana, Rebecca Taylor,<br>Gaby Casteneda, and Jenny Mangaly
		<br><i>with mentoring by Mike Coutermarsh</i></p>
	</div>
</div>

<div class="blurbs">
	<div class="tools-intro text-center">
		<h1>THE TOOLSET</h1>
		<h5>these awesome integrations have helped us along the way:</h5>
	</div>
	<br>
	<div class="col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-2">
		<%= image_tag("github-logo.png") %>
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
		<%= image_tag("slack-logo.png") %>
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-1">
		<%= image_tag("travisCI-logo.png") %>
	</div>

	<div class="subsequent-row col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-3">
		<%= image_tag("trello-logo.png") %>
	</div>
	<div class="subsequent-row col-xs-10 col-xs-offset-1 col-sm-2 col-sm-offset-0">
		<%= image_tag("codeclimate-logo.png") %>
	</div>

	<div class="subsequent-row bottom col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-5">
	<%= image_tag("rubo-logo.png") %>
	</div>
</div>

<hr width="60%" noshade>

<div class="open-games col-xs-10 col-xs-offset-1 text-center">
	<h2><b>Are there any games I can join?</b></h2>
		<% if @games.present? %>
			<h4>Yes, there are! You can join any of these:</h4>
			<% @games.each do |game| %>
				<h5><%= link_to 'Pick me!', game_path(game) %></h5>
			<% end %>
			<h2> Want to start a new game?	</h2>
				<p> To start a new game! Click <%= link_to 'here', games_path, :method => :post %></p>
		<% else %>
			<h4>No, sorry. :( Check back later, or create your own game!</h4>
			<h4> To start a new game! Click <%= link_to 'here', games_path, :method => :post %></h4>
		<% end %>
</div>

<hr width="60%" noshade>

<div class="blurbs text-center about">
	<h1>about the team</h1>
</div>

<div class="bios">
	<div class="about">
		<div class="yan descript col-xs-10 col-xs-offset-1 col-sm-5">
			<h3>yan hu</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum ac nunc a maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ornare mi tristique, sollicitudin mauris eget, tempor arcu. Donec egestas metus diam, sit amet feugiat purus laoreet ac. Ut suscipit, nisi vel finibus consectetur, dui massa imperdiet nisl, id feugiat elit tellus vel orci.</p>
		</div>
		<div class="yan pic col-xs-10 col-xs-offset-1 col-sm-4">
			<%= image_tag("codeclimate-logo.png") %>
		</div>
	</div>

		<div class="clearfix"></div>

	<div class="about">
		<div class="eric pic col-xs-10 col-xs-offset-1 col-sm-4">
			<%= image_tag("codeclimate-logo.png") %>
		</div>
		<div class="eric descript col-xs-10 col-xs-offset-1 col-sm-5">
			<h3>eric orellana</h3>
			<p> Eric is a passionate coder. He is always willing to assist others on the team and get on a Skype session. He loves to review code, learn how to do it better, and work through difficult problems.</p>
		</div>
	</div>

		<div class="clearfix"></div>

	<div class="about">
		<div class="rebecca descript col-xs-10 col-xs-offset-1 col-sm-5">
			<h3>rebecca taylor</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum ac nunc a maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ornare mi tristique, sollicitudin mauris eget, tempor arcu. Donec egestas metus diam, sit amet feugiat purus laoreet ac. Ut suscipit, nisi vel finibus consectetur, dui massa imperdiet nisl, id feugiat elit tellus vel orci.</p>
		</div>
		<div class="rebecca pic col-xs-10 col-xs-offset-1 col-sm-4">
			<%= image_tag("codeclimate-logo.png") %>
		</div>
	</div>

		<div class="clearfix"></div>

	<div class="about">
		<div class="jenny pic col-xs-10 col-xs-offset-1 col-sm-4">
			<%= image_tag("codeclimate-logo.png") %>
		</div>
		<div class="jenny descript col-xs-10 col-xs-offset-1 col-sm-5">
			<h3>jenny mangaly</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum ac nunc a maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ornare mi tristique, sollicitudin mauris eget, tempor arcu. Donec egestas metus diam, sit amet feugiat purus laoreet ac. Ut suscipit, nisi vel finibus consectetur, dui massa imperdiet nisl, id feugiat elit tellus vel orci.</p>
		</div>
	</div>

	<div class="clearfix"></div>

	<div class="about">
		<div class="gaby descript col-xs-10 col-xs-offset-1 col-sm-5">
			<h3>gaby casteneda</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum ac nunc a maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ornare mi tristique, sollicitudin mauris eget, tempor arcu. Donec egestas metus diam, sit amet feugiat purus laoreet ac. Ut suscipit, nisi vel finibus consectetur, dui massa imperdiet nisl, id feugiat elit tellus vel orci.</p>
		</div>
		<div class="gaby pic col-xs-10 col-xs-offset-1 col-sm-4">
			<%= image_tag("codeclimate-logo.png") %>
		</div>
	</div>

	<div class="clearfix"></div>

	<div class="footer text-center">
		<p><i><div class="reg-font">&copy;</div> 2016<i></p>
	</div>
</div>

app/views/games/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a New Game</h1>
  <br />
  <%= simple_form_for @game, :url => games_path do |f| %>
<!-- removed the form field to collect name because we don't have a name field in the game-->
    <br />
    <%= f.submit "Create", :class => 'btn btn-primary pull-right' %>
    <br />
  <% end %>
<br />
</div>

app/views/games/show.html.erb
<div id="chess">
  <h1>Jedi Chess</h1>
    <table>
      <!-- create a 8x8 table using ruby loops, for each td tag, also insert the id with the position value such as a8, b6, c3..etc. The id will be used to insert the pieces later -->
      <% y_array = (1..8).to_a.reverse! %>
      <% y_array.each do |y_value| %>
        <%= content_tag "tr" do %>
          <% x_array = ('A'..'H').to_a %>
          <% x_array.each do |x_value| %>
            <% pos_id = x_value + y_value.to_s %>
            <%= content_tag "td", id: pos_id do %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </table>
</div>